name: "❓ Consulta General o Pregunta Técnica"
description: "Haz preguntas sobre la arquitectura, cómo clonar el proyecto o consultas del desarrollo."
title: "[QUESTION]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        ¿Tienes dudas sobre la arquitectura, compilación o funcionamiento interno de **Mental Math**? Pregunta aquí.

  - type: textarea
    id: question
    attributes:
      label: Tu Pregunta o Consulta
      description: Describe tu duda claramente.
      placeholder: ¿Cómo se maneja el estado de la racha diaria entre Room y el ViewModel de Home?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Contexto Adicional
      description: Si estás intentando compilar o aprender de un componente específico, indícalo.
    validations:
      required: false
